//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WagenparkMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class auto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public auto()
        {
            this.onderhoud = new HashSet<onderhoud>();
        }
    
        public string kenteken { get; set; }
        public string merk { get; set; }
        public string Type { get; set; }
        public int DEALER_dealernr { get; set; }
    
        public virtual dealer dealer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<onderhoud> onderhoud { get; set; }
    }
}
